name: Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag/Version name'
        required: true
        type: string

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.LPBAISER_GITHUB_TOKEN }}

      - name: Update changelog and package version
        run: |
          sed -i '3 i \\n## [${{ inputs.tag }}](https://github.com/${{ github.repository }}/releases/tag/${{ inputs.tag }})' CHANGELOG.md
          sed -i 's/"version": "*.*.*"/"version": "${{ inputs.tag }}"/g' package.json

      - name: Commit changes to chosen branch
        run: |
          git config user.name lpbaiser
          git config user.email lpbaiser@gmail.com
          git stage .
          git commit -m "Release version ${{ inputs.tag }}"
          git push

      - name: Create tag
        run: |
          git tag ${{ inputs.tag }}
          git push origin ${{ inputs.tag }}